"""Reading the offers out of a board's alert.

An alert is a list, and until now it arrived as one opaque blob a person had to
re-read on the board's own site. This turns it back into rows.

Every board is parsed from the message's **plain-text** part rather than its
HTML. That part is generated by the board from the same data, it survives
forwarding intact, and it has no markup to drift under us — a redesign changes
the HTML every season and the text part almost never.

The shape the plain text takes is always the same: a link to the offer,
followed by the fields as bare lines. So the link is the anchor. It also
carries the board's own identifier for the offer, which is the only dedupe key
worth having: the same offer reaches you twice under two different titles
("Specjalista ds. IT" in the daily digest, "! Specjalista ds. IT" in the
recommendations) and the id is identical both times.

Nothing here guesses. A board we have no parser for yields no offers and the
message stays in the inbox as it arrived, which is the honest outcome — a
half-parsed offer costs more to correct than to enter.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, replace

from app.ingest.grounding import amount_present, flatten, present

# `<https://…>` — the plain-text part wraps every link in angle brackets.
LINK = re.compile(r"<(https?://[^>\s]+)>")
# The alt text the text-part generator leaves where an image was.
IMAGE = re.compile(r"^\[image:[^\]]*\]$")

# Boards mark a promoted row with a leading glyph that is not part of the title.
TITLE_NOISE = re.compile(r"^[!*•\-•]+\s*")

# Tracking that should not follow the offer into the database. `sendid` ties the
# row to one delivery of one email to one person; there is no reason to keep it.
TRACKING = re.compile(r"^(utm_|sendid$|send_date$|trk$|refId$|ref$|position$|pageNum$)", re.I)


@dataclass(frozen=True)
class Salary:
    """An advertised range, in the units the advert used.

    Kept as the board printed it rather than normalised to a monthly gross
    figure: "24 zł netto / godz." and "4 000 zł brutto / mies." are not
    comparable without knowing hours and tax, and inventing that conversion
    would put a number in front of someone that no employer ever said.
    """

    minimum: float | None
    maximum: float | None
    currency: str = "PLN"
    kind: str | None = None  # salary_kind: gross | net
    period: str | None = None  # salary_period: hour | month | year


@dataclass(frozen=True)
class ParsedOffer:
    """One offer, as much of it as the alert actually said.

    `external_id` is the board's identifier, not ours. It is what makes the
    same offer arriving in tomorrow's digest the same row.
    """

    external_id: str
    title: str
    url: str
    company: str | None = None
    location: str | None = None
    salary: Salary | None = None


def extract(body: str, source: str | None) -> list[ParsedOffer]:
    """The offers an alert lists, in the order it listed them."""
    parser = PARSERS.get(source or "")
    if parser is None:
        return []
    return parser(body or "")


def clean_url(url: str) -> str:
    """The offer's address without the campaign that delivered it."""
    head, sep, query = url.partition("?")
    if not sep:
        return head
    kept = [pair for pair in query.split("&") if pair and not TRACKING.match(pair.split("=", 1)[0])]
    return head + ("?" + "&".join(kept) if kept else "")


def _fields_by_offer(body: str, identify) -> dict[str, list[str]]:
    """Walk the text collecting the lines that follow each offer's links.

    The plain-text part repeats the same link before the title, the company and
    the location, so the link is a cursor: whatever bare line comes next belongs
    to whichever offer was last named. A link that identifies no offer — the
    "more offers" search link, a footer link — clears the cursor, so the chrome
    around the list is attributed to nobody.
    """
    fields: dict[str, list[str]] = {}
    current: str | None = None
    expecting = False

    for raw in body.splitlines():
        line = raw.strip()
        if not line:
            continue

        link = LINK.fullmatch(line) or LINK.search(line)
        if link and line.startswith("<"):
            current = identify(link.group(1))
            expecting = current is not None
            if current is not None:
                fields.setdefault(current, [])
            continue

        if IMAGE.match(line):
            continue

        if expecting and current is not None:
            # Only the first line after a link: taking every line until the next
            # one would sweep up the section headings that sit between offers.
            fields[current].append(line)
            expecting = False

    return fields


# ── identity ─────────────────────────────────────────────────────────

# Where each board keeps its own id in the address. Used by both the rules
# below and the model-backed reader, so an offer gets the same identity
# whichever of them saw it first.
BOARD_IDS = {
    "pracuj": re.compile(r"/praca/[^,\s]*,oferta,(\d+)"),
    "protocol": re.compile(r"theprotocol\.it/[^,\s]*,oferta,([a-z0-9]+)", re.I),
    "linkedin": re.compile(r"linkedin\.com/(?:comm/)?jobs/view/(\d+)"),
    "justjoin": re.compile(r"justjoin\.it/(?:job|offers)/([a-z0-9-]+)", re.I),
    "rocketjobs": re.compile(r"rocketjobs\.pl/oferta/([a-z0-9-]+)", re.I),
    "nofluff": re.compile(r"nofluffjobs\.com/(?:[a-z]{2}/)?job/([a-z0-9-]+)", re.I),
    "olx": re.compile(r"olx\.pl/d/oferta/[^/\s]*-ID([A-Za-z0-9]+)"),
}


def board_id(url: str) -> str | None:
    """The board's own identifier for this advert, if the link carries one.

    None means the link is not an advert — a search, an unsubscribe, a footer
    link — which is how the chrome around a listing is told from the listing.
    """
    for prefix, pattern in BOARD_IDS.items():
        found = pattern.search(url)
        if found:
            return f"{prefix}:{found.group(1)}"
    return None


def identify(url: str) -> str:
    """A stable identity for an advert, falling back to its address.

    Two alerts linking the same advert link it the same way, so the cleaned
    address is a serviceable key for a board whose id we cannot pick out.
    """
    return board_id(url) or clean_url(url)


# ── pracuj.pl ────────────────────────────────────────────────────────


def _pracuj(body: str) -> list[ParsedOffer]:
    urls: dict[str, str] = {}

    def pick(url: str) -> str | None:
        found = BOARD_IDS["pracuj"].search(url)
        if not found:
            return None
        offer_id = f"pracuj:{found.group(1)}"
        urls.setdefault(offer_id, clean_url(url))
        return offer_id

    return _assemble(_fields_by_offer(body, pick), urls)


def _assemble(fields: dict[str, list[str]], urls: dict[str, str]) -> list[ParsedOffer]:
    """Turn the collected lines into offers, dropping anything without a title.

    The lines are classified rather than counted off by position. A board only
    prints the salary line when the advert declared one, so the offer above it
    has three lines and the offer below it has four — assuming position put a
    company name where the money was and the money where the city should be.
    """
    offers = []
    for offer_id, lines in fields.items():
        money, rest = None, []
        for line in lines:
            found = read_salary(line)
            if found is not None and money is None:
                money = found
            else:
                rest.append(line)

        if not rest:
            continue
        title = TITLE_NOISE.sub("", rest[0]).strip()
        if not title:
            continue

        offers.append(
            ParsedOffer(
                external_id=offer_id,
                title=title,
                url=urls.get(offer_id, ""),
                company=rest[1] if len(rest) > 1 else None,
                location=rest[2] if len(rest) > 2 else None,
                salary=money,
            )
        )
    return offers


# "6 000-10 000 zł brutto / mies.", "24 zł netto / godz.", "12 000 PLN"
AMOUNT = r"\d[\d  .,]*\d|\d"
SALARY_LINE = re.compile(
    rf"(?P<low>{AMOUNT})\s*(?:[-–—]\s*(?P<high>{AMOUNT}))?\s*"
    r"(?P<currency>z[łl]|PLN|EUR|USD|€|\$)",
    re.I,
)
KIND_WORDS = {"brutto": "gross", "gross": "gross", "netto": "net", "net": "net"}
PERIOD_WORDS = {
    "godz": "hour",
    "h": "hour",
    "hour": "hour",
    "mies": "month",
    "miesi": "month",
    "month": "month",
    "mth": "month",
    "rok": "year",
    "roczn": "year",
    "year": "year",
}
CURRENCIES = {
    "zł": "PLN",
    "zl": "PLN",
    "pln": "PLN",
    "eur": "EUR",
    "€": "EUR",
    "usd": "USD",
    "$": "USD",
}


def read_salary(line: str) -> Salary | None:
    """A salary line, or None if this line is a company or a city.

    Deliberately strict about needing a currency: a company called "Grupa 4"
    and a street address both carry digits, and mistaking either for money puts
    a wrong number on a row someone will later negotiate against.
    """
    found = SALARY_LINE.search(line)
    if not found:
        return None

    lowered = line.lower()
    return Salary(
        minimum=_number(found.group("low")),
        maximum=_number(found.group("high")) if found.group("high") else None,
        currency=CURRENCIES.get(found.group("currency").lower(), "PLN"),
        kind=next((v for k, v in KIND_WORDS.items() if k in lowered), None),
        period=next((v for k, v in PERIOD_WORDS.items() if k in lowered), None),
    )


def _number(text: str | None) -> float | None:
    if not text:
        return None
    # Polish adverts group thousands with spaces and use a comma for decimals.
    cleaned = text.replace(" ", "").replace(" ", "").replace(",", ".")
    # A trailing dot is a sentence, not a decimal point.
    cleaned = cleaned.rstrip(".")
    try:
        return float(cleaned)
    except ValueError:
        return None


PARSERS = {
    "pracuj_pl": _pracuj,
}


# ── grounding ────────────────────────────────────────────────────────


def ground(candidates: list[ParsedOffer], body: str) -> list[ParsedOffer]:
    """Keep only what the message actually says.

    Applied to whatever produced the candidates — a model or the rules above.
    The rules cannot invent anything, so for them this is a no-op that costs
    microseconds; for a model it is the whole safety story. Running it on both
    means there is one answer to "can this field be trusted", not two.

    Losing a field is not losing the offer: an advert with an unreadable city
    is still worth triaging. Losing the title or the link is losing the offer,
    because neither can be recovered by looking at the row later.
    """
    haystack = flatten(body)
    kept = []

    for offer in candidates:
        # The link is compared without its query: the stored URL has had the
        # delivery's tracking stripped, so it is deliberately not the string
        # that appears in the message. Everything before the `?` still is.
        address, _, _ = offer.url.partition("?")
        if not present(offer.title, haystack) or not present(address, haystack):
            continue

        money = offer.salary
        if money is not None and not (
            amount_present(money.minimum, haystack) and amount_present(money.maximum, haystack)
        ):
            money = None

        kept.append(
            replace(
                offer,
                company=offer.company if present(offer.company, haystack) else None,
                location=offer.location if present(offer.location, haystack) else None,
                salary=money,
            )
        )

    return kept
